<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3.00_img</name>
   <tag></tag>
   <elementGuidId>59b925dc-032f-423a-ad50-e93e9ee1dcd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-1-panel-3']/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-1-panel-3 > div.txn-history > div.table-wrap > div.ant-row.arts-gridrow > div.ant-col.ant-col-xs-24.ant-col-sm-24.ant-col-md-6 > div.listing-item > div.img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a6796e8-ae0c-46e8-8706-7067da839583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0cb96062-c941-4624-ba1f-344fbad70711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-panel-3&quot;)/div[@class=&quot;txn-history&quot;]/div[@class=&quot;table-wrap&quot;]/div[@class=&quot;ant-row arts-gridrow&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-sm-24 ant-col-md-6&quot;]/div[@class=&quot;listing-item&quot;]/div[@class=&quot;img&quot;]</value>
      <webElementGuid>0a6e00b9-1ab2-40ff-96d0-7586c7229001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-panel-3']/div/div/div/div/div/div</value>
      <webElementGuid>5d07cae0-00c1-456c-8957-2bce96cae750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>dfe70321-38e1-451c-aa29-2afb628c68aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
