<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Listings</name>
   <tag></tag>
   <elementGuidId>8b5413bc-d958-41a3-8ad1-0ae0f5fb29c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/a[5]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9103409c-3ca0-4cae-a5b6-19e494093282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listings</value>
      <webElementGuid>ecc63fc1-14d0-47a3-81e4-68ac53ccaf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;admin&quot;]/div[@class=&quot;main-view&quot;]/div[@class=&quot;admin-sidebar&quot;]/a[@class=&quot;admin-link&quot;]/p[1]</value>
      <webElementGuid>66be5c90-950f-4877-bc94-8255cbbdc522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/a[5]/p</value>
      <webElementGuid>0670440b-ba88-4072-800b-b18d72a06287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AA'])[1]/preceding::p[5]</value>
      <webElementGuid>0f6e532c-03ec-49ad-8099-e779ebd885a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Account'])[1]/preceding::p[5]</value>
      <webElementGuid>7a139393-0ac5-44cc-9f57-b82ca8a5c892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Listings']/parent::*</value>
      <webElementGuid>802f4197-7211-4299-80af-9d95d9284832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/p</value>
      <webElementGuid>280e845b-5842-4dae-b03b-000275d0a189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Listings' or . = 'Listings')]</value>
      <webElementGuid>31eabca0-7d93-4496-bdf4-f472b4d0c4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
